/**
 * THE POEMS — one a day, on the onyx wall.
 *
 * Plain words, short lines, concrete nouns, and a turn at the end that
 * is never a moral. Bukowski's register, not his biography: the bar and
 * the horses are his, the bike and the humidity and the district office
 * are Dr Non's.
 *
 * Drawn from the wisdom projects — dao, mean, ninja, slowdown — and from
 * the life underneath them: Shanghai fieldwork in Yangpu, fourteen years
 * in Boston never having paid tuition, a father who died in 2010, cities
 * measured by people who do not live in them, a Brompton, a lot of
 * coffee.
 *
 * House rules from CLAUDE.md §12.4 apply and are not negotiable here:
 * no motivational fluff, no business words, no quantified feelings, no
 * packaged vulnerability, and no ending that ties itself off. The poem
 * stops; it does not conclude.
 *
 * One per day, chosen by date so it is the same poem all day on every
 * device — a poem that changes while you are reading it is a gimmick.
 */

export const POEMS = [
  {
    t: 'THE SURVEY',
    l: ['They came to measure the neighbourhood.',
        'Clipboards. A drone. Two days.',
        'They counted doors and trees',
        'and the width of the lane.',
        '',
        'Mrs Chen has lived here forty years.',
        'Nobody asked her anything.',
        'She watched from the step',
        'the way you watch weather.',
        '',
        'The report says the area is underutilised.',
        'She is still on the step.'],
  },
  {
    t: 'RENT',
    l: ['I never paid for school.',
        'Somebody always did — a fund,',
        'a foundation, a dead man\'s money',
        'with his name on the envelope.',
        '',
        'Fourteen years of that.',
        'You would think it feels like freedom.',
        '',
        'It feels like a debt',
        'with no address to send it to.'],
  },
  {
    t: 'YANGPU, WINTER',
    l: ['No heating in that building.',
        'You wrote with a coat on',
        'and your hand went stupid by four.',
        '',
        'Downstairs the old men played cards',
        'in the cold like it was nothing,',
        'because it was nothing,',
        'because they were from here',
        'and I was the one taking notes.',
        '',
        'I went to study the architecture.',
        'I came back unable to write about a building',
        'without writing about who was cold in it.'],
  },
  {
    t: 'SMART',
    l: ['The city is getting smart.',
        'Sensors on the poles.',
        'A dashboard in a room',
        'nobody walks past.',
        '',
        'The bus is still late.',
        'The bus was always late.',
        'Now we know precisely how late,',
        'to the second, in colour.'],
  },
  {
    t: 'MY FATHER\'S WATCH',
    l: ['It ran four minutes fast.',
        'He liked that. Said it bought him',
        'four minutes.',
        '',
        'When he died I did not fix it.',
        'I wear it wrong on purpose',
        'and I am early to everything',
        'and it has never once',
        'bought me anything.'],
  },
  {
    t: 'THE GOOD CHAIR',
    l: ['Mies made a chair',
        'that costs more than a car',
        'so that two kings could sit',
        'for eleven minutes in 1929.',
        '',
        'The kings left.',
        'They knocked the building down',
        'the following year.',
        '',
        'We rebuilt it in 1986',
        'from photographs',
        'because we could not stand',
        'that it was gone.',
        '',
        'That is the whole story of architecture.'],
  },
  {
    t: 'TRAFFIC',
    l: ['Forty minutes to go three kilometres.',
        'The man beside me is eating rice',
        'off his lap, steering with a knee.',
        '',
        'In the meeting I will say',
        'the word "mobility" eleven times.',
        '',
        'He is the one who is mobile.',
        'He is having lunch.'],
  },
  {
    t: 'SLOW',
    l: ['I got the folding bike',
        'to be faster.',
        '',
        'What happened instead:',
        'I found out the market smells',
        'different at each end,',
        'that the canal turns',
        'where the road pretends it does not,',
        'and that a city you can smell',
        'is not the city on the map.',
        '',
        'I am not faster.',
        'I just know where I am.'],
  },
  {
    t: 'CREDENTIALS',
    l: ['MIT. Oxford. Harvard.',
        'People relax when they hear it,',
        'the way you relax',
        'when a stranger shows a badge.',
        '',
        'It means I sat in some rooms.',
        'It does not mean I was right',
        'in any of them.',
        '',
        'Non means not.',
        'I did not pick the name',
        'but I have grown into it.'],
  },
  {
    t: 'THE MEETING',
    l: ['Everyone agreed.',
        'That was the problem.',
        '',
        'Nine people in a room',
        'and not one of them',
        'wanted to be the one',
        'who had read the appendix.',
        '',
        'It is in the appendix.',
        'It is always in the appendix.'],
  },
  {
    t: 'RAIN, SUKHUMVIT',
    l: ['It comes at four like a decision.',
        'The street becomes a river',
        'and the motorbikes go anyway,',
        'plastic bags for shoes.',
        '',
        'A tourist films it, appalled.',
        'The noodle woman does not look up.',
        'She has seen this river',
        'ten thousand times',
        'and it has never once',
        'taken her stall.'],
  },
  {
    t: 'BOOKS',
    l: ['Three hundred in five years.',
        'People say that like it is a lot.',
        '',
        'It is one at a time,',
        'mostly on a train,',
        'mostly the same three questions',
        'asked by different dead people',
        'who also did not know.'],
  },
  {
    t: 'WHAT THE DASHBOARD SAYS',
    l: ['Green. Green. Green. Amber.',
        '',
        'The amber is a pump in a district',
        'I have never been to,',
        'and somebody there',
        'is standing in water',
        'right now',
        'while I decide whether',
        'to open the panel.'],
  },
  {
    t: 'OFFICE HOURS',
    l: ['The department opens at eight-thirty.',
        'The queue starts at six.',
        '',
        'We are digitising the form.',
        'The form will be beautiful.',
        'It will take four minutes.',
        '',
        'The queue will still start at six',
        'because the queue was never',
        'about the form.'],
  },
  {
    t: 'IT WOULD BE OKAY',
    l: ['It would be okay if I died today.',
        '',
        'Not a brave thing to say.',
        'Not a sad one either.',
        '',
        'Just: the coffee was good,',
        'the work is unfinished',
        'the way work is,',
        'and somebody else',
        'will have opinions about the bus.'],
  },
  {
    t: 'THE PHOTOGRAPH',
    l: ['A man on a scooter',
        'carrying a ladder,',
        'a dog, and a child.',
        '',
        'Western colleagues call it charming.',
        'The traffic police call it a violation.',
        'He calls it Tuesday.',
        '',
        'Three true descriptions.',
        'Only one of them',
        'has to get home.'],
  },
  {
    t: 'MEASUREMENT',
    l: ['We rank one hundred and sixty-three cities.',
        'Someone always asks',
        'where their city came.',
        '',
        'Nobody asks what we left out.',
        '',
        'We left out whether you can walk',
        'to see your mother.',
        'We could not find the data.'],
  },
  {
    t: 'THE OLD SHOPHOUSE',
    l: ['Teak, termites, a bad roof,',
        'and a stairway you must turn sideways for.',
        '',
        'The developer calls it a constraint.',
        'The grandmother calls it the stairs.',
        '',
        'One of them is going to win',
        'and we both know which,',
        'and the drawing is already done.'],
  },
  {
    t: 'PRODUCTIVITY',
    l: ['Twenty-five minutes, then a break.',
        'I have done four of these today',
        'and moved one sentence.',
        '',
        'The sentence is better.',
        '',
        'No system on earth',
        'will tell you whether',
        'that was worth the morning.'],
  },
  {
    t: 'COFFEE, 6 A.M.',
    l: ['Before the phone.',
        'Before the exchange rate,',
        'the group chats,',
        'the man who needs the slides.',
        '',
        'Ten minutes when the day',
        'has not been assigned to anyone.',
        '',
        'This is the whole practice.',
        'There is no other part.'],
  },
  {
    t: 'THE CONSULTANT',
    l: ['They flew him in for two days.',
        'He said the thing',
        'the local team had said',
        'for four years,',
        'and everyone wrote it down.',
        '',
        'He was not wrong.',
        'That is the part',
        'that keeps me up.'],
  },
  {
    t: 'INHERITANCE',
    l: ['No children, so people ask',
        'who it is all for.',
        '',
        'The bus runs at six for someone.',
        'The pump holds for someone.',
        'The kid in the district office',
        'who fixes the form after me —',
        'her.',
        '',
        'It is a poor answer at dinner',
        'and a good one at work.'],
  },
  {
    t: 'LUGGAGE',
    l: ['New Zealand. They lost the bag.',
        'Everything in it. Whole trip ruined,',
        'I said, out loud, to a woman',
        'whose job was not to care.',
        '',
        'The insurance paid ten times',
        'what the bag was worth.',
        '',
        'I still say things are ruined.',
        'I have just stopped believing myself',
        'quite so fast.'],
  },
  {
    t: 'THE ROOM YOU ARE IN',
    l: ['A roof on eight thin columns.',
        'Walls that hold nothing up',
        'and therefore stop wherever they like.',
        '',
        'That is the trick, and it is not a trick:',
        'take the weight off a thing',
        'and it is free to be any shape.',
        '',
        'I have not managed it yet',
        'with a week.'],
  },
];

/**
 * The poem for a given day. Deterministic, so it is the same poem all
 * day on every device someone opens this on — and so tomorrow's is
 * genuinely tomorrow's, not a reshuffle on every reload.
 */
export function poemForDate(d = new Date(), tz = 'Asia/Bangkok') {
  const ymd = new Intl.DateTimeFormat('en-CA', { timeZone: tz }).format(d);
  const days = Math.floor(Date.parse(ymd + 'T00:00:00Z') / 86400000);
  return { ...POEMS[((days % POEMS.length) + POEMS.length) % POEMS.length], index: days % POEMS.length };
}
